name: Gradle Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gradle
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Build & Test with Gradle
        run: "gradle build"
