name: "Gradle Build"
on: ["push"]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    container:
      image: "gradle"
    steps:
      - uses: "actions/checkout@v2"
        name: "Checkout"
      - name: "Build & Test with Gradle"
        run: "gradle build"
      - uses: "actions/upload-artifact@v2"
        name: "Upload Build Artifact"
        with:
          name: "Plugin Artifact"
          path: "/home/runner/work/hardcore-plugin/hardcore-plugin/build/libs/Hardcore-*.jar"
      - uses: "softprops/action-gh-release@v1"
        name: "Upload Release Artifact"
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          files: "/home/runner/work/hardcore-plugin/hardcore-plugin/build/libs/Hardcore-*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
